
package view;

import controller.ProjectController;
import javax.swing.JOptionPane;
import model.Project;
import model.User;

/**
 *
 * @author ton618
 */
public class ProjectDialogRegisterScreen extends javax.swing.JDialog {

    ProjectController controller;
    private User user;
    
    public ProjectDialogRegisterScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        controller = new ProjectController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProjectTitlePanel = new javax.swing.JPanel();
        ProjectTitle = new javax.swing.JLabel();
        SaveProject = new javax.swing.JLabel();
        DataPanelProject = new javax.swing.JPanel();
        ProjectName = new javax.swing.JTextField();
        ProjectDescriptionPanel = new javax.swing.JScrollPane();
        ProjectDescription = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ProjectTitlePanel.setBackground(new java.awt.Color(0, 155, 102));

        ProjectTitle.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        ProjectTitle.setForeground(java.awt.Color.white);
        ProjectTitle.setText(" Save project");

        SaveProject.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SaveProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/check/check (4).png"))); // NOI18N
        SaveProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveProjectMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ProjectTitlePanelLayout = new javax.swing.GroupLayout(ProjectTitlePanel);
        ProjectTitlePanel.setLayout(ProjectTitlePanelLayout);
        ProjectTitlePanelLayout.setHorizontalGroup(
            ProjectTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjectTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProjectTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SaveProject, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ProjectTitlePanelLayout.setVerticalGroup(
            ProjectTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjectTitlePanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(ProjectTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SaveProject, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(ProjectTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        DataPanelProject.setBackground(java.awt.Color.white);

        ProjectName.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));

        ProjectDescription.setColumns(20);
        ProjectDescription.setRows(5);
        ProjectDescription.setBorder(javax.swing.BorderFactory.createTitledBorder("Descrição"));
        ProjectDescriptionPanel.setViewportView(ProjectDescription);

        javax.swing.GroupLayout DataPanelProjectLayout = new javax.swing.GroupLayout(DataPanelProject);
        DataPanelProject.setLayout(DataPanelProjectLayout);
        DataPanelProjectLayout.setHorizontalGroup(
            DataPanelProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataPanelProjectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DataPanelProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProjectName)
                    .addComponent(ProjectDescriptionPanel))
                .addContainerGap())
        );
        DataPanelProjectLayout.setVerticalGroup(
            DataPanelProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataPanelProjectLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(ProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ProjectDescriptionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProjectTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DataPanelProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ProjectTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DataPanelProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveProjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveProjectMouseClicked
        
        try {
            if (!ProjectName.getText().isEmpty()) {
                //creating a new project
                Project project = new Project();

                //setting the fild values to the brend new project
                project.setName(ProjectName.getText());
                project.setDescription(ProjectDescription.getText());
                project.setProjectUser(user.getUserID());

                //saving the new project
                controller.save(project);

                //show the sucess saved message
                JOptionPane.showMessageDialog(rootPane,
                        "Projeto salvo com sucesso!");

                //closing the window
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, 
                        "Preencha o campo nome!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,
                    e.getMessage());
        }        
    }//GEN-LAST:event_SaveProjectMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogRegisterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogRegisterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogRegisterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogRegisterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProjectDialogRegisterScreen dialog = new ProjectDialogRegisterScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DataPanelProject;
    private javax.swing.JTextArea ProjectDescription;
    private javax.swing.JScrollPane ProjectDescriptionPanel;
    private javax.swing.JTextField ProjectName;
    private javax.swing.JLabel ProjectTitle;
    private javax.swing.JPanel ProjectTitlePanel;
    private javax.swing.JLabel SaveProject;
    // End of variables declaration//GEN-END:variables
    public void setUser(User user) {
        this.user = user;
    }
}
